=== rafacrespo/Entregar-XML-del-canal-TDT/xmltv.dtd
<!ELEMENT tv (channel*, programme*)>
<!ATTLIST tv date   CDATA #IMPLIED
             source-info-url     CDATA #IMPLIED
             source-info-name    CDATA #IMPLIED
             source-data-url     CDATA #IMPLIED
             generator-info-name CDATA #IMPLIED
             generator-info-url  CDATA #IMPLIED >

<!ELEMENT channel (display-name+, icon*, url*) >
<!ATTLIST channel id CDATA #REQUIRED >

<!ELEMENT display-name (#PCDATA)>
<!ATTLIST display-name lang CDATA #IMPLIED>

<!ELEMENT icon EMPTY>
<!ATTLIST icon src         CDATA #REQUIRED
               width       CDATA #IMPLIED
               height      CDATA #IMPLIED>

<!ELEMENT url (#PCDATA)>
<!ATTLIST url system CDATA #IMPLIED>

<!ELEMENT programme (title+, sub-title*, desc*, credits?, date?,
                     category*, keyword*, language?, orig-language?,
                     length?, icon*, url*, country*, episode-num*,
                     video?, audio?, previously-shown?, premiere?,
                     last-chance?, new?, subtitles*, rating*,
                     star-rating*, review*, image* )>
<!ATTLIST programme start     CDATA #REQUIRED
                    stop      CDATA #IMPLIED
                    pdc-start CDATA #IMPLIED
                    vps-start CDATA #IMPLIED
                    showview  CDATA #IMPLIED
                    videoplus CDATA #IMPLIED
                    channel   CDATA #REQUIRED
                    clumpidx  CDATA "0/1" >


<!ELEMENT title (#PCDATA)>
<!ATTLIST title lang CDATA #IMPLIED>

<!ELEMENT sub-title (#PCDATA)>
<!ATTLIST sub-title lang CDATA #IMPLIED>

<!ELEMENT desc (#PCDATA)>
<!ATTLIST desc lang CDATA #IMPLIED>

<!ELEMENT credits (director*, actor*, writer*, adapter*, producer*,
                   composer*, editor*, presenter*, commentator*,
                   guest* )>
<!ELEMENT director    (#PCDATA | image | url)* >
<!ELEMENT actor       (#PCDATA | image | url)* >
<!ATTLIST actor role  CDATA      #IMPLIED
                guest (no | yes) #IMPLIED >
<!ELEMENT writer      (#PCDATA | image | url)* >
<!ELEMENT adapter     (#PCDATA | image | url)* >
<!ELEMENT producer    (#PCDATA | image | url)* >
<!ELEMENT composer    (#PCDATA | image | url)* >
<!ELEMENT editor      (#PCDATA | image | url)* >
<!ELEMENT presenter   (#PCDATA | image | url)* >
<!ELEMENT commentator (#PCDATA | image | url)* >
<!ELEMENT guest       (#PCDATA | image | url)* >


<!ELEMENT date (#PCDATA)>

<!ELEMENT category (#PCDATA)>
<!ATTLIST category lang CDATA #IMPLIED>


<!ELEMENT keyword (#PCDATA)>
<!ATTLIST keyword lang CDATA #IMPLIED>

<!ELEMENT language (#PCDATA)>
<!ATTLIST language lang CDATA #IMPLIED>


<!ELEMENT orig-language (#PCDATA)>
<!ATTLIST orig-language lang CDATA #IMPLIED>

<!ELEMENT length (#PCDATA)>
<!ATTLIST length units (seconds | minutes | hours) #REQUIRED>

<!ELEMENT country (#PCDATA)>
<!ATTLIST country lang CDATA #IMPLIED>

<!ELEMENT episode-num (#PCDATA)>
<!ATTLIST episode-num system CDATA "onscreen">

<!ELEMENT video (present?, colour?, aspect?, quality?)>
<!ELEMENT present (#PCDATA)>
<!ELEMENT colour (#PCDATA)>
<!ELEMENT aspect (#PCDATA)>
<!ELEMENT quality (#PCDATA)>

<!ELEMENT audio (present?, stereo?)>
<!ELEMENT stereo (#PCDATA)>

<!ELEMENT previously-shown EMPTY>
<!ATTLIST previously-shown start   CDATA #IMPLIED
                           channel CDATA #IMPLIED >

<!ELEMENT premiere (#PCDATA)>
<!ATTLIST premiere lang CDATA #IMPLIED>

<!ELEMENT last-chance (#PCDATA)>
<!ATTLIST last-chance lang CDATA #IMPLIED>

<!ELEMENT new EMPTY>

<!ELEMENT subtitles (language?)>
<!ATTLIST subtitles type (teletext | onscreen | deaf-signed) #IMPLIED>

<!ELEMENT rating (value, icon*)>
<!ATTLIST rating system CDATA #IMPLIED>

<!ELEMENT value (#PCDATA)>

<!ELEMENT star-rating (value, icon*)>
<!ATTLIST star-rating system CDATA #IMPLIED>

<!ELEMENT review (#PCDATA)>
<!ATTLIST review type     (text | url) #REQUIRED
                 source   CDATA        #IMPLIED
                 reviewer CDATA        #IMPLIED
                 lang     CDATA        #IMPLIED>

<!ELEMENT image (#PCDATA)>
<!ATTLIST image type ( poster | backdrop | still | person | character ) #IMPLIED>
<!ATTLIST image size ( 1 | 2 | 3 ) #IMPLIED>
<!ATTLIST image orient ( P | L ) #IMPLIED>
<!ATTLIST image system CDATA #IMPLIED>

=== rafacrespo/Entregar-XML-del-canal-TDT/la1.tv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv>
<channel id="LaSexta.TV">
<display-name>LaSexta.TV</display-name>
</channel>

<programme channel="LaSexta.TV" start="20240206025500 +0000" stop="20240206053000 +0000">
<title>Aruseros</title>
<desc>Magacine de actualidad en tono de humor</desc>
<category>Informacion</category>
<language>es</language>
<icon src="https://www.movistarplus.es/recorte/n/caratula4/MSEXTAP661411"/>
</programme>

<programme channel="LaSexta.TV" start="20240206025500 +0000" stop="20240206053000 +0000">
<title>Al Rojo Vivo</title>
<desc>Programa de actualidad presentado por Antonio García Ferreras.</desc>
<category>Informacion</category>
<language>es</language>
<icon src="https://www.movistarplus.es/recorte/n/caratula4/MSEXTAP3067053"/>
</programme>

<programme channel="LaSexta.TV" start="20240206025500 +0000" stop="20240206053000 +0000">
<title>LaSexta Noticias</title>
<desc>Los informativos de La Sexta 1ª Edición corren a cargo de Helena Resano.</desc>
<category>Informacion</category>
<language>es</language>
<icon src="https://www.movistarplus.es/recorte/n/caratula4/MSEXTAP3241102"/>
</programme>

<programme channel="LaSexta.TV" start="20240206025500 +0000" stop="20240206053000 +0000">
<title>Sexta Noche</title>
<desc>El programa laSexta Noche, ahora laSexta Xplica, se emitía todos los sábados en horario nocturno en laSexta</desc>
<category>Informacion</category>
<language>es</language>
<icon src="https://www.movistarplus.es/recorte/n/caratula4/MSEXTAP3241104"/>
</programme>
</tv>

=== rafacrespo/Entregar-XML-del-canal-TDT/tv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv>
<channel id="La1.TV">
<display-name>La1.TV</display-name>
</channel>

<programme channel="La1.TV" start="20240206173000 +0000" stop="20240206183000 +0000">
<title>El cazador</title>
<desc> Concurso de preguntas y respuestas en el que concursantes anónimos luchan frente a un concursante profesional de la televisión para obtener un gran premio final. En el programa, los cuatro concursantes unirán sus conocimientos para ganar al 'cazador'</desc>
<category>Entretenimiento</category>
<language>es</language>
<icon src="https://www.movistarplus.es/recorte/n/caratula4/MTVEP2070065"/>
</programme>

<programme channel="La1.TV" start="20240207094000 +0000" stop="20240207130000 +0000">
<title>Mañaneros</title>
<desc>Magazín de actualidad conducido por Jaime Cantizano, que tiene el afán de contar temas de interés para el ciudadano, desde la actualidad política a la crónica social.</desc>
<category>Entretenimiento</category>
<language>es</language>
<icon src="https://www.movistarplus.es/recorte/n/caratula4/MTVEP3108161"/>
</programme>

<programme channel="La1.TV" start="20240207131000 +0000" stop="20240207140000 +0000">
<title>Ahora o nunca</title>
<desc>Espacio diario que presume de la riqueza del país y animará al espectador a disfrutar y a conservarlo para garantizar que siga existiendo para los que vengan detrás.</desc>
<category>Entretenimiento</category>
<language>es</language>
<icon src="https://www.movistarplus.es/recorte/n/caratula4/MTVEP3218310"/>
</programme>

<programme channel="La1.TV" start="20240207193000 +0000" stop="20240207200000 +0000">
<title>Aquí la Tierra</title>
<desc>Jacob Petrus ofrece una original mirada sobre el territorio y sus habitantes a través de la meteorología. La divulgación y la información sobre el terreno conviven con el descubrimiento de la naturaleza y el medio ambiente.</desc>
<category>Entretenimiento</category>
<language>es</language>
<icon src="https://www.movistarplus.es/recorte/n/caratula4/MTVEP3218312"/>
</programme>
</tv>
